services:
  retroarch:
    image: docker-box:latest
    container_name: docker-box  
    restart: unless-stopped
    runtime: runc
    ## NOTE: Requires privileged access to host to be able to access the required devices
    privileged: true
    shm_size: 2G
    ipc: host # Could also be set to 'shareable'
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    network_mode: host
    hostname: docker-box
    extra_hosts:
      - "docker-box:127.0.0.1"
    environment:
      - NAME=docker-box #Hostname
      - TZ=Asia/Novosibirsk #TZ for RetroArch and container
      - DISPLAY=:55 
      - PUID=1000 # User UID for running a container
      - PGID=1000 # User GID for running a container
      - UMASK=000
      - WEB_UI_MODE=vnc # "vnc" for NoVNC, "none" for no debugging
      - PORT_NOVNC_WEB=8083 # NoVNC listening address
      - SUNSHINE_USER=user # Sunshine User in WebUI
      - SUNSHINE_PASS=pass # Sunshine User in WebUI
 #   env_file: .env
    volumes:
      # The location of your home directory.
      - ./docker-box/home/:/home/default/:rw
      # Input devices used for mouse and joypad support inside the container.
      - /dev/input/:/dev/input/:ro
      # The Xorg socket. This will be shared with other containers so they can access the X server.
      - ./docker-box/.X11-unix/:/tmp/.X11-unix/:rw
      # Pulse audio socket. This will be shared with other containers so they can access the audio sink.
      - ./docker-box/pulse/:/tmp/pulse/:rw
       # Persistent storage for retroarch configs/cores/etc
#      - ./docker-box/retroarch/:/home/default/.config/retroarch/
       # The location with games
      - /mnt/Vault101_2/Games101/:/mnt/Games/:ro

      
