
# Optionally launch directly to steam big picture (disabled by default)
[program:steam]
priority=50
autostart=false
autorestart=false
# Retry a restart a few times.
#   This allows this container to start up before X is ready and restart the process until it becomes available.
#   Each restart will have a small delay of a few seconds. So 50 attempts should be a few mins.
startretries=50
user=%(ENV_USER)s
directory=/home/%(ENV_USER)s
command=/usr/games/steam %(ENV_STEAM_ARGS)s
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
stopsignal=INT
stdout_logfile=/dev/null
stdout_logfile_maxbytes=0

stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
