services:
  docker-box:
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    container_name: docker-box
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 5096M
    device_cgroup_rules:
      - c 13:* rwm
      - c 226:* rwm
    devices:
      - /dev/dri/:/dev/dri/
      - /dev/fuse:/dev/fuse
      - /dev/uinput:/dev/uinput
    environment:
      FORCE_X11_DUMMY_CONFIG: 'true'
      GID: '568'
      GROUP_ID: '568'
      PGID: '568'
      PUID: '568'
      SELKIES_ENCODER: vah264enc
      SUNSHINE_PASS: test
      SUNSHINE_USER: test
      UID: '568'
      USER_ID: '568'
      USER_LOCALES: en_US.UTF-8 UTF-8
      USER_PASSWORD: test
    extra_hosts:
      server101: 127.0.0.1
    group_add:
      - 44
      - 107
      - 568
    hostname: server101
    image: docker-box:latest
    ipc: host
    network_mode: host
    privileged: True
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    shm_size: 2048M
    ulimits:
      nofile:
        hard: 524288
        soft: 1024
    volumes:
      - /mnt/apps101/docker101/steamheadless/home:/home/default:rw
      - /mnt/apps101/docker101/steamheadless/games:/mnt/games:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/pulse:/tmp/pulse:rw
      - /dev/input/:/dev/input/:ro
