services:
  steam-headless:
    container_name: steam-headless
    image: josh5/steam-headless:latest
    hostname: server101
    restart: unless-stopped
    network_mode: host
    ipc: host
    privileged: true
#    runtime: nvidia # For NVIDIA
    device_cgroup_rules:
      - 'c 10:* rmw'    # uinput
      - 'c 13:* rmw'    # input (event devices
    group_add:
      - 44
      - 107
      - 568
    shm_size: 2048M
    ulimits:
      nofile:
        hard: 524288
        soft: 1024
    environment:
      GID: '568'
      GROUP_ID: '568'
      PGID: '568'
      PUID: '568'
      UID: '568'
      USER_ID: '568'
      SUNSHINE_USER: 'test'
      SUNSHINE_PASS: 'test'
      USER_PASSWORD: 'test'
      PORT_NOVNC_WEB: '31100'
      TZ: Asia/Novosibirsk
    extra_hosts:
      server101: 127.0.0.1
    volumes:
      - /mnt/apps101/docker101/steamheadless/home:/home/default:rw
      - /mnt/apps101/docker101/steamheadless/games:/mnt/games:rw
      - /mnt/apps101/docker101/steamheadless/tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/apps101/docker101/steamheadless/tmp/pulse:/tmp/pulse:rw
      - /dev/input/:/dev/input/:rw
      - /run/udev:/run/udev:ro
      - /mnt/vault101/vault101/Games101/Emulation:/mnt/vault101/vault101/Games101/Emulation:rw
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M