services:
  docker-box:
    container_name: docker-box
    image: docker-box:latest
    hostname: server101
    restart: unless-stopped
    network_mode: host
    ipc: host
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    device_cgroup_rules:
      - c 13:* rwm
      - c 226:* rwm
    group_add:
      - 44
      - 107
      - 568
    shm_size: 2048M
    ulimits:
      nofile:
        hard: 524288
        soft: 1024
    devices:
      - /dev/dri/:/dev/dri/
      - /dev/fuse:/dev/fuse
      - /dev/uinput:/dev/uinput
    environment:
      FORCE_X11_DUMMY_CONFIG: 'true'
      GID: '568'
      GROUP_ID: '568'
      PGID: '568'
      PUID: '568'
      UID: '568'
      USER_ID: '568'
    extra_hosts:
      server101: 127.0.0.1
    volumes:
      - /mnt/apps101/docker101/steamheadless/home:/home/default:rw
      - /mnt/apps101/docker101/steamheadless/games:/mnt/games:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/pulse:/tmp/pulse:rw
      - /dev/input/:/dev/input/:ro
      - /mnt/vault101/vault101/Games101/Emulation:/mnt/vault101/vault101/Games101/Emulation:rw
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 5096M
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]