name: build_and_publish

on:
  push:
    branches:
      - 'master'

jobs:
  docker_publish:
    runs-on: "self-hosted"

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for docker-box
        uses: quaigoner/docker-box@master
        with:
          image_name: docker-box  # it will be lowercased internally
          github_token: ${{ secrets.TOKEN }}
          